### PR TITLE
Redesign

### PR DESCRIPTION
**Pull request by jodosha**
A big thank you to [Alan Tippins](http://www.alantippins.com) who donated his work to us. :sparkles: :clap: :sparkles: 

# Home

home

---

# Blog

blog

---

# Article

article

### CODE REVIEW

**Comment by jodosha** [comment]
Here a preview of the **Guides** section. 
**This needs to be filled with contents before to be deployed**

guides

**Comment by robyurkowski** [comment]
Man, I'm just so impressed with Alan's work. Those guides look amazing!

**Comment by jc00ke** [comment]
Wow, looks great!

**Comment by Linuus** [comment]
Looks very nice! :+1:

**Comment by joneslee85** [comment]
Such wow, so great

**Comment by jodosha** [comment]
This is the Community preview:

community

**Comment by jodosha** [comment]
This is the old home page:

lotus

**Comment by jodosha** [comment]
Deployed! :shipit:

**Pull request merged**
